export enum ErrorCode {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  MANAGER_NOT_MEMBER_OF_DEPARTMENT = 'MANAGER_NOT_MEMBER_OF_DEPARTMENT',
  MANAGER_NOT_FOUND = 'MANAGER_NOT_FOUND',
  DEPARTMENT_ALREADY_EXISTS = 'DEPARTMENT_ALREADY_EXISTS',
  MANAGER_ALREADY_MANAGES_DEPARTMENT = 'MANAGER_ALREADY_MANAGES_DEPARTMENT',
}
